# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63e20951fcf5da37eccb442e1064317706272923dd807339e7ffc21677d6e2e396eef7b092ae5d0119a7a2a9c168b9eb36f2bef781c235fc325c3aa68a2c042f

test:
  secret_key_base: 8c3e16cd4f45d71c6691cc2a2fa21204751895f00635604dedf0a0f39a3900a88a58dfd94987216a80d042296c07859365da32e26417192671e8ba95b82596e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
